# -*- coding: utf-8 -*-
# This script was auto-generated by Sim4Life version 8.0.0.15035

import numpy as np
import s4l_v1.model as model
from XCore import Color

rgb = np.load(r'C:/Users/tharayil/Downloads/rgb_percentActivation(1).npy')

ents = model.AllEntities()

iteration = 1

for i in range(39):

	if i == 0:
	
		ents['Fascicles'].Color = Color(*tuple(rgb[i+39*iteration]))
	
	else:

		ents['Fascicles '+str(i)].Color = Color(*tuple(rgb[i+39*iteration]))